spring:
  application:
    name: ms-candidate
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:candidates_db}?createDatabaseIfNotExist=true&useSSL=false
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    placeholder-replacement: true
    locations: classpath:db/migration

security:
  jwt:
    key:
      private: cbd345d6a2815fa88d1022650386d07488f45c6c5c3d72da1ca380f0808bb15f
    user:
      generator: richard  


server:
  port: 8080
