spring:
  datasource:
    url: jdbc:mysql://localhost:3306/candidates_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    placeholder-replacement: true
    locations: classpath:db/migration

security:
  jwt:
    key:
      private: cbd345d6a2815fa88d1022650386d07488f45c6c5c3d72da1ca380f0808bb15f
    user:
      generator: richard  


server:
  port: 8080
